# Introdução à Ciência de Dados - UFPB
Professor: Yuri Malheiros

## NumPy

Implemente a função `distance` abaixo. Ela deve receber dois pontos e retornar a distância euclidiana entre eles. Cada ponto é representado por um array do NumPy, por exemplo, `p1 = np.array([2,4])` representa o ponto com coordenadas `x=2` e `y=2`.

In [2]:
import numpy as np

def distance(p1, p2):
    """
    >>> distance(np.array([0,0]), np.array([1,1]))
    1.4142135623730951
    
    >>> distance(np.array([1,2]), np.array([3,4]))
    2.8284271247461903
    
    >>> distance(np.array([5,2]), np.array([-2,-1]))
    7.615773105863909
    """

    # ADICIONE O SEU CÓDIGO AQUI
    # dAB² = (xB – xA)² + (yB – yA)². 

    d = np.sum(np.square(p1 - p2))
    
    return (np.sqrt(d))

Implemente a função `n_distances` abaixo. Ela recebe um ponto (`p1`), como um array do NumPy, e uma lista de pontos (`points`), uma matriz do NumPy, onde cada linha representa um ponto.

Esta função deve retornar a distância de `p1` para todos os pontos da matriz `points`. O retorno é uma lista, onde cada elemento tem a distância de `p1` para o ponto daquela posição correspondente.

In [44]:
def n_distances(p1, points):
    """
    >>> n_distances(np.array([0,0]), np.array([[1,1]]))
    array([1.41421356])
    
    >>> n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
    array([1.41421356, 2.82842712])
    
    >>> n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
    """
    
    # ADICIONE O SEU CÓDIGO AQUI
    
    d = np.sqrt(np.sum(np.square(points - p1), axis=1))
    
    return np.array(d.tolist())

Implemente a função `sort_by_distances`. Assim como a função anterior, ela recebe um ponto (`p1`), como um array do NumPy, e uma lista de pontos (`points`), uma matriz do NumPy, onde cada linha representa um ponto.

Esta função deve retornar uma matriz com os valores de `points` ordenados de acordo com as suas distâncias para `p1`, ou seja, a primeira linha da matriz de retorno deve ser o ponto mais próximo de `p1`, a segunda linha deve ser segundo ponto mais próximo de `p1` e assim sucessivamente.

In [54]:
def sort_by_distances(p1, points):
    """
    >>> sort_by_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
    array([[2,1], [3,-1], [5, 2], [-2, -5], [10, 1]])

    >>> sort_by_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
    array([[1,1], [2,2]])
    """
    
    # ADICIONE O SEU CÓDIGO AQUI
    
    distances = np.array(n_distances(p1, points))
    sorted_indices = np.argsort(distances)

    return points[sorted_indices]

sort_by_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))

array([[ 2,  1],
       [ 3, -1],
       [ 5,  2],
       [-2, -5],
       [10,  1]])

In [53]:
np.argsort??

## Teste

In [45]:
import doctest

doctest.testmod(verbose=True)

Trying:
    distance(np.array([0,0]), np.array([1,1]))
Expecting:
    1.4142135623730951
ok
Trying:
    distance(np.array([1,2]), np.array([3,4]))
Expecting:
    2.8284271247461903
ok
Trying:
    distance(np.array([5,2]), np.array([-2,-1]))
Expecting:
    7.615773105863909
ok
Trying:
    n_distances(np.array([0,0]), np.array([[1,1]]))
Expecting:
    array([1.41421356])
ok
Trying:
    n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
Expecting:
    array([1.41421356, 2.82842712])
ok
Trying:
    n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
Expecting:
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
ok
Trying:
    sort_by_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
Expecting:
    array([[2,1], [3,-1], [5, 2], [-2, -5], [10, 1]])
**********************************************************************
File "__main__", line 3, in __main__.sort_by_distances
Failed example:
    sort_by_distanc

TestResults(failed=2, attempted=8)