# Vetores

# Complexidade de cálculos vetoriais
**Operadores de ponto flutuante**. Sabemos que

$$(a+b)(a-b) = a^2-b^2 \qquad \forall \, a, b\in \mathbb{R}.$$

Quando um computador calcula o lado esquerdo e o lado direito, para $a$ e $b$, não necessariamente são iguais, devido a erros de arredondamento de ponto flutuante muito pequenos. Mas eles devem ser quase iguais.

In [1]:
a = rand();
b = rand();
esquerda = (a+b) * (a-b)

0.43487977794520144

In [2]:
direita = a^2 - b^2

0.4348797779452014

In [42]:
esquerda == direita # não são iguais, mas muito próximos.

false

**Complexidade**. Podemos cronometrar um comando em Julia adicionando ```@time```. O cronômetro não é muito preciso para tempos muito pequenos, medidos em microssegundos $(10^{-6} {\rm segundos})$. Além disso, você deve executar este comando mais de uma vez; pois pode ser muito mais rápido nas seguintes execuções.

In [64]:
a = randn(10^5); 
b = randn(10^5);
@time a'*b

  0.000187 seconds (2 allocations: 32 bytes)


-238.03662461889752

In [5]:
@time a'*b

  0.000336 seconds (2 allocations: 32 bytes)


171.32307974320707

In [6]:
c = randn(10^6); 
d = randn(10^6);
@time c'*d

  0.000833 seconds (2 allocations: 32 bytes)


-704.8128259647635

In [7]:
@time c'*d

  0.000673 seconds (2 allocations: 32 bytes)


-704.8128259647635

**Vetores esparsos**. As funções para criar e manipular vetores esparsos estão contidas no pacote SparseArrays do Julia, então você precisa instalar este pacote antes de poder usá-los.

Os vetores esparsos são armazenados como arrays esparsos, ou seja, arrays nos quais apenas os elementos diferentes de zero são armazenados. Em Julia você pode criar um vetor esparso a partir de listas de índices e valores usando a função ```sparsevec```. Você também pode primeiro criar um vetor esparso de zeros (usando ```spzeros(n)```) e então atribuir valores às entradas diferentes de zero. 

Um vetor esparso pode ser criado a partir de um vetor não esparso usando ```sparse(x)```, que retorna uma versão esparsa de ```x```.

In [8]:
using SparseArrays #Para manipular vetores esparsos

In [65]:
a = sparsevec([123456, 123457],[1.0,-1.0], 10^6) #  cria um vetor esparso a partir de listas de índices e valores

1000000-element SparseVector{Float64, Int64} with 2 stored entries:
  [123456 ]  =  1.0
  [123457 ]  =  -1.0

In [66]:
length(a)

1000000

In [67]:
nnz(a) # número de elementos diferentes de zero de um vetor esparso

2

In [69]:
b = randn(10^6) #Um ordinario (vetor não-esparso)
@time 2*a #Calculado de forma eficiente!

  0.000018 seconds (3 allocations: 192 bytes)


1000000-element SparseVector{Float64, Int64} with 2 stored entries:
  [123456 ]  =  2.0
  [123457 ]  =  -2.0

In [70]:
@time 2*b

  0.023094 seconds (2 allocations: 7.629 MiB, 92.49% gc time)


1000000-element Vector{Float64}:
  1.5503635739808665
  1.9920683095898488
  0.9964363430123953
  1.7973134934664896
 -0.8041892174683543
 -0.2868979102325832
 -1.6909445437419244
 -1.6774893172211287
  2.1633444267459585
  1.5856762093268821
  0.6540198407438688
 -0.3721282553054695
  1.5261048933215025
  ⋮
  2.3293241106718856
 -2.0980783098937326
 -1.5092502161180685
 -0.30078868653183616
  1.8279718908407443
  0.2882300594148363
  1.2766533666811493
 -2.855277897388561
 -1.1226030488516252
 -2.274483703318295
 -0.5287013777166433
  0.7598555257116776

In [71]:
sb = sparse(b) # cria uma versão esparsa apartir do vetor não esparso b 

1000000-element SparseVector{Float64, Int64} with 1000000 stored entries:
  [1      ]  =  0.775182
  [2      ]  =  0.996034
  [3      ]  =  0.498218
  [4      ]  =  0.898657
  [5      ]  =  -0.402095
  [6      ]  =  -0.143449
  [7      ]  =  -0.845472
  [8      ]  =  -0.838745
  [9      ]  =  1.08167
  [10     ]  =  0.792838
             ⋮
  [999990 ]  =  -1.04904
  [999991 ]  =  -0.754625
  [999992 ]  =  -0.150394
  [999993 ]  =  0.913986
  [999994 ]  =  0.144115
  [999995 ]  =  0.638327
  [999996 ]  =  -1.42764
  [999997 ]  =  -0.561302
  [999998 ]  =  -1.13724
  [999999 ]  =  -0.264351
  [1000000]  =  0.379928

In [72]:
@time a'*sb

  0.000160 seconds (2 allocations: 48 bytes)


-3.1016965681100492

In [16]:
@time a'*b

  0.010659 seconds (37.78 k allocations: 2.053 MiB, 96.45% compilation time)


0.7028344924052492

In [17]:
@time b'*b

  0.000437 seconds (2 allocations: 32 bytes)


999011.0256445078

In [18]:
@time c = a + b

  0.333408 seconds (1.59 M allocations: 115.924 MiB, 10.83% gc time, 90.36% compilation time)


1000000-element SparseVector{Float64, Int64} with 1000000 stored entries:
  [1      ]  =  -2.01238
  [2      ]  =  -0.519354
  [3      ]  =  -1.00251
  [4      ]  =  1.29474
  [5      ]  =  0.507438
  [6      ]  =  -0.318947
  [7      ]  =  -0.399074
  [8      ]  =  -0.6763
  [9      ]  =  -0.377782
  [10     ]  =  -0.626285
             ⋮
  [999990 ]  =  3.74333
  [999991 ]  =  1.85377
  [999992 ]  =  -0.739253
  [999993 ]  =  1.75258
  [999994 ]  =  -0.191247
  [999995 ]  =  0.802288
  [999996 ]  =  -0.069844
  [999997 ]  =  -1.24182
  [999998 ]  =  -0.0161188
  [999999 ]  =  0.008581
  [1000000]  =  -0.602286

Na última linha, o vetor esparso a é convertido automaticamente em um vetor comum (array) para que possa ser adicionado ao vetor aleatório; o resultado é um vetor (não esparso) de comprimento $10^6$.

In [19]:
spzeros(10^6) + c

1000000-element SparseVector{Float64, Int64} with 1000000 stored entries:
  [1      ]  =  -2.01238
  [2      ]  =  -0.519354
  [3      ]  =  -1.00251
  [4      ]  =  1.29474
  [5      ]  =  0.507438
  [6      ]  =  -0.318947
  [7      ]  =  -0.399074
  [8      ]  =  -0.6763
  [9      ]  =  -0.377782
  [10     ]  =  -0.626285
             ⋮
  [999990 ]  =  3.74333
  [999991 ]  =  1.85377
  [999992 ]  =  -0.739253
  [999993 ]  =  1.75258
  [999994 ]  =  -0.191247
  [999995 ]  =  0.802288
  [999996 ]  =  -0.069844
  [999997 ]  =  -1.24182
  [999998 ]  =  -0.0161188
  [999999 ]  =  0.008581
  [1000000]  =  -0.602286

In [20]:
using LinearAlgebra

# Norma e distancia
### Norma
**Norm.** A norma $‖x‖$ em Julia é `norm(x)`.  A função `norm`  esta definida no package `LinearAlgebra`.

In [73]:
x = [ 2, -1, 2 ];
norm(x), sqrt(x'*x), sqrt(sum(x.^2))

(3.0, 3.0, 3.0)

In [22]:
norm(x, 1),   # Norma 1
norm(x, Inf), # Norma infinito
norm(x, 2),   # Norma Euclideana
norm(x, 4)    # Norma induzida p=4

(5.0, 2.0, 3.0, 2.39678172692843)

**Desigualdade Triangular.** 

$$‖x+ y‖ ≤ ‖x‖+ ‖y‖\qquad \forall\, x, y \in \mathbb{R}^n$$

In [99]:
x = randn(10); 
y = randn(10);
esquerdo = norm(x+y)
direito = norm(x) + norm(y)
esquerdo, direito

(4.791562860865834, 5.898581575758053)

**Exemplo:** Função média aritmética

In [101]:
media(x) = (ones(length(x)) / length(x))'*x;
x = [1, -3, 2, -1, 2, 4, 10];
media(x)

2.1428571428571423

### Distancia

**Distancia:**  A distancia entre dois vetores é ${\rm dist}(x, y) = ‖x − y‖$. Em Julia é `norm(x-y)`.

In [102]:
u = [1.8, 2.0, -3.7, 4.7];
v = [0.6, 2.1, 1.9, -1.4];
w = [2.0, 1.9, -4.0, 4.6];
norm(u-v), norm(u-w), norm(v-w)

(8.36779540858881, 0.3872983346207417, 8.532877591996735)

**Exemplo:(Vizinho mais Proximo)** Defimos uma função que calcula o vizinho mais proximo de um vetor em uma lista de vetores.

In [104]:
vizinho_proximo(x,z) = z[ argmin([norm(x-y) for y in z]) ]; # argmin retorna o menor indice do vetor

z = ( [2,1], [7,2], [5.5,4], [4,8], [1,5], [9,6]);

vizinho_proximo([7,2], z)

2-element Vector{Int64}:
 7
 2

In [105]:
vizinho_proximo([3,3], z)

2-element Vector{Int64}:
 2
 1

Na primeira linha, a expressão `[norm(x-y) for y in z]` usa uma construção conveniente em Julia. Aqui `z` é uma lista de vetores, e a expressão expande para um array com elementos `norm(x-z[1])`, `norm(x-z[2]),`,... A função `argmin` aplicada a este array retorna o indice do menor elemento.

### Angulo entre vetores

In [106]:
# Defimos a função angulo, a qual retorna radianos
ang(x,y) = acos(x'*y/(norm(x)*norm(y)));
a = [1,2,-1]; b=[2,0,-3];

[(ang(a,b),":angulo em radianos"), 
(ang(a,b)*(360/(2*pi)), ":angulo in graus")]

2-element Vector{Tuple{Float64, String}}:
 (0.9689825515916383, ":angulo em radianos")
 (55.51861062801842, ":angulo in graus")

### Vetores Ortonormais
**Expansão em uma base ortonormal:** Dados os vetores
$$
a_1 = \begin{bmatrix} 0\\ 0\\ -1\end{bmatrix}, 
a_2 = \frac{1}{\sqrt{2}}\begin{bmatrix} 1\\ 1\\ 0 \end{bmatrix},
a_3 = \frac{1}{\sqrt{2}}\begin{bmatrix} 1\\ -1\\ 0\end{bmatrix}
$$

verifiquemos se formam uma base ortonormal, e vejamos a expansão de $x = \begin{bmatrix} 1\\ 2\\ 3\end{bmatrix}$ em esta base,

$$x = (a^{T}_{1} x)a_1 + · · ·+ (a^{T}_{n}x)a_n.$$

In [110]:
a1 = [0,0,-1]; a2 = [1,1,0]/sqrt(2); a3 = [1,-1,0]/sqrt(2);
norm(a1), norm(a2), norm(a3)

(1.0, 0.9999999999999999, 0.9999999999999999)

In [111]:
a1'*a2, a1'*a3, a2'*a3

(0.0, 0.0, -2.2371143170757382e-17)

In [112]:
x = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [113]:
# obtendo os coeficientes de x na base ortonormal
beta1 = a1'*x; 
beta2 = a2'*x; 
beta3 = a3'*x

# Expansão de x na base
xexp = beta1*a1 + beta2*a2 + beta3*a3

3-element Vector{Float64}:
 0.9999999999999999
 1.9999999999999996
 3.0

## O  Algoritmo de Gram–Schmidt

Consideremos como entrada um array `[ a[1], a[2] ,..., a[k] ]`, contendo os $k$ vetores $a_1, \ldots , a_k$. 

- Se os vetores são  L.I., retorna um array `[ q[1] ,..., q[k] ]` com o conjunto ortonormal dos vetores calculado pelo algoritmo de Gram–Schmidt. 
- Se os vetores são L.D e o algoritmo de Gram–Schmidt termina antes na iteração `i`, este retorna um array `[ q[1],..., q[i] ]` de comprimento `i`.

In [114]:
function gram_schmidt(a; tol = 1e-10)
    
    q = []           # inicializamos o array de saida como um array vazio
    for i = 1:length(a)
        qtilde = a[i]
        for j = 1:i-1
            qtilde -= (q[j]'*a[i]) * q[j]
        end
        if norm(qtilde) < tol
            println("Os vetores são linearmente dependentes.")
            return q
        end
        push!(q, qtilde/norm(qtilde))    #Em cada iteração, adicionamos o seguinte vetor ao array usando a função push!
        end;
    return q
end

gram_schmidt (generic function with 1 method)

**Exemplo:** 

In [115]:
a = [ [1, 0, 1], [1, 0, 0], [2, 1, 0] ]

3-element Vector{Vector{Int64}}:
 [1, 0, 1]
 [1, 0, 0]
 [2, 1, 0]

In [116]:
q = gram_schmidt(a)

3-element Vector{Any}:
 [0.7071067811865475, 0.0, 0.7071067811865475]
 [0.7071067811865477, 0.0, -0.7071067811865474]
 [-2.220446049250313e-16, 1.0, 2.220446049250313e-16]

In [117]:
a = [ [-1, 1, -1, 1], [-1, 3, -1, 3], [1, 3, 5, 7] ]

3-element Vector{Vector{Int64}}:
 [-1, 1, -1, 1]
 [-1, 3, -1, 3]
 [1, 3, 5, 7]

In [118]:
q = gram_schmidt(a)

3-element Vector{Any}:
 [-0.5, 0.5, -0.5, 0.5]
 [0.5, 0.5, 0.5, 0.5]
 [-0.5, -0.5, 0.5, 0.5]

In [119]:
# teste de ortnormalidade

[("norm(q[1]:)",norm(q[1])),
("q[1]'*q[2]:",q[1]'*q[2]),
("q[1]'*q[3]:",q[1]'*q[3]),
("norm(q[2]):",norm(q[2])),
("q[2]'*q[3]:",q[2]'*q[3]),
("norm(q[3]):",norm(q[3]))]

6-element Vector{Tuple{String, Float64}}:
 ("norm(q[1]:)", 1.0)
 ("q[1]'*q[2]:", 0.0)
 ("q[1]'*q[3]:", 0.0)
 ("norm(q[2]):", 1.0)
 ("q[2]'*q[3]:", 0.0)
 ("norm(q[3]):", 1.0)

**Exemplo de finalização antecipada:** Se subtituimos $a_3$ com a combinação linear de $a_1$, e $a_2$ o conjunto será L.D.

In [120]:
b = [ a[1], a[2], 1.3*a[1] + 0.5*a[2] ]

3-element Vector{Vector{Float64}}:
 [-1.0, 1.0, -1.0, 1.0]
 [-1.0, 3.0, -1.0, 3.0]
 [-1.8, 2.8, -1.8, 2.8]

In [121]:
q = gram_schmidt(b)

Os vetores são linearmente dependentes.


2-element Vector{Any}:
 [-0.5, 0.5, -0.5, 0.5]
 [0.5, 0.5, 0.5, 0.5]

**Exemplo:** Sabemos que quaisquer 3 vetores em $\mathbb{R}^2$ debem ser L.D. Usemos o algoritmo de Gram-Schmidt para verificar este fato.

In [41]:
vetores = [ [1,1], [1,2], [-1,1] ];
q = gram_schmidt(vetores)

Os vetores são linearmente dependentes.


2-element Vector{Any}:
 [0.7071067811865475, 0.7071067811865475]
 [-0.7071067811865471, 0.7071067811865478]